
USE [CUNGCAP_VLXD]
GO

CREATE TRIGGER [dbo].[TR_KHO]
ON [dbo].[Kho]
AFTER INSERT, UPDATE
AS
DECLARE @MADL VARCHAR(10)
DECLARE @MAKHO VARCHAR(10)
DECLARE @MADLNEW VARCHAR(10)
BEGIN
	
	DECLARE @SODL INT = (SELECT COUNT(MaDL) FROM DaiLy)
	SET @MAKHO = (SELECT MAKHO FROM inserted)
	SET @MADLNEW = (SELECT MADL FROM inserted)
	IF(@SODL >1) 
		BEGIN 
			IF(@MAKHO LIKE 'K'+@MADLNEW+'%' AND @MAKHO < (CONCAT('KDL',@SODL)))
				BEGIN
					PRINT(N'THÀNH CÔNG')
				END
			ELSE
				BEGIN
					PRINT(N'LỖI')
					ROLLBACK TRAN
				END
		END
	ELSE
		BEGIN
			SET @MADL = (SELECT DL.MaDL FROM DaiLy AS DL)
			DECLARE @CHECKMAKHO VARCHAR(10) = 'K'+ @MADL
			IF(@MAKHO LIKE @CHECKMAKHO + '%' AND @MADL = @MADLNEW)
				BEGIN
					PRINT(N'THÀNH CÔNG')
				END
			ELSE
				BEGIN
					PRINT(N'LỖI')
					ROLLBACK TRAN
				END
		END
END