USE CUNGCAP_VLXD
GO
CREATE FUNCTION [dbo].[CheckMaNhanVien] (@MADL VARCHAR(10), @MANV VARCHAR(10))
RETURNS BIT
AS
BEGIN
	DECLARE @CHECK_MANV VARCHAR(10) = 'NV'+@MADL
	IF (@MANV LIKE @CHECK_MANV +'%') RETURN 1
	RETURN 0;
END
--SELECT [dbo].[CheckMaNhanVien]('DL1', 'NVDL2003')
CREATE TRIGGER [dbo].[TR_NHANVIEN]
ON [dbo].[NhanVien]
AFTER INSERT, UPDATE
AS 
DECLARE @MADL VARCHAR(10), @MANV VARCHAR(10), @MADLNEW VARCHAR(10), @SO INT
SET @SO = (SELECT COUNT(MaDL) FROM DaiLy)
SET @MANV = (SELECT MANV FROM inserted)
SET @MADLNEW = (SELECT MADL FROM inserted)
IF  @SO > 1 
BEGIN
	DECLARE @MA VARCHAR(10) = CONCAT('NVDL', @SO)
	IF (@MANV < @MA and @MANV LIKE 'NV'+ @MADLNEW +'%')
	BEGIN
		PRINT N'THÀNH CÔNG'
	END
	ELSE 
		BEGIN
			PRINT N'THẤT BẠI, YÊU CẦU NHẬP MÃ NHÂN VIÊN Ở ĐẠI LÝ 1 BẮT ĐẦU BẰNG: NVDL VÀ NHỎ HON'+ @MA
			ROLLBACK TRAN
		END
END
ELSE
BEGIN
	SET @MADL = (SELECT DaiLy.MaDL FROM DaiLy)
	IF ([dbo].[CheckMaNhanVien](@MADL, @MANV)=1 and @MADL = @MADLNEW)
		BEGIN
			PRINT N'THÀNH CÔNG'
		END
	ELSE 
		BEGIN 
			PRINT N'THẤT BẠI, YÊU CẦU NHẬP MÃ NHÂN VIÊN Ở ĐẠI LÝ BẮT ĐẦU BẰNG: NV'+@MADL
			ROLLBACK TRAN
		END
END

