CREATE TRIGGER TR_DONGIA_VATLIEU
ON DBO.CTPMH
AFTER INSERT, UPDATE
AS
BEGIN
    UPDATE DBO.CTPMH
    SET DBO.CTPMH.DONGIA = DBO.VatLieu.DongiaVL
    FROM DBO.CTPMH
    INNER JOIN DBO.VatLieu ON DBO.CTPMH.MAVL = DBO.VatLieu.MAVL
    WHERE DBO.CTPMH.MAVL IN (SELECT MAVL FROM inserted)
END