use CUNGCAP_VLXD
go
CREATE TRIGGER [dbo].[TR_NHANVIEN]
ON [dbo].[NHANVIEN]
AFTER INSERT, UPDATE
AS 

DECLARE @MADL VARCHAR(10)
DECLARE @MANV VARCHAR(10)
DECLARE @SO INT
SET @SO = (SELECT COUNT(MaDL) FROM DaiLy)
SET @MANV = (SELECT MANV FROM inserted)
IF  @SO > 1 
BEGIN
	DECLARE @MA VARCHAR(10)
	SET @MA = CONCAT('NVDL', @SO)
	IF (@MANV LIKE 'NVDL%' and @MANV < @MA)
	BEGIN
		PRINT N'THÀNH CÔNG'
	END
	ELSE 
		BEGIN
			PRINT N'THẤT BẠI, YÊU CẦU NHẬP MÃ NHÂN VIÊN Ở ĐẠI LÝ 1 BẮT ĐẦU BẰNG: NVDL VÀ NHỎ HON MÃ'+ @MA
			ROLLBACK TRAN
		END
END

ELSE
BEGIN
	SET @MADL = (SELECT DaiLy.MaDL FROM DaiLy)
	
	IF @MADL ='DL1'
	BEGIN
		IF (@MANV LIKE 'NVDL1%')
			BEGIN
				PRINT N'THÀNH CÔNG'
			END
		ELSE 
			BEGIN 
				PRINT N'THẤT BẠI, YÊU CẦU NHẬP MÃ NHÂN VIÊN Ở ĐẠI LÝ 1 BẮT ĐẦU BẰNG: NVDL1'
				ROLLBACK TRAN
			END
	END
	----DL2
	ELSE IF @MADL ='DL2'
	BEGIN
		IF (@MANV LIKE 'NVDL2%')
			BEGIN
				PRINT N'THÀNH CÔNG'
			END
		ELSE 
			BEGIN 
				PRINT N'THẤT BẠI, YÊU CẦU NHẬP MÃ NHÂN VIÊN Ở ĐẠI LÝ 2 BẮT ĐẦU BẰNG: NVDL2'
				ROLLBACK TRAN
			END
	END
	----DL3
	ELSE IF @MADL ='DL3'
	BEGIN
		IF (@MANV LIKE 'NVDL3%')
			BEGIN
				PRINT N'THÀNH CÔNG'
			END
		ELSE 
			BEGIN 
				PRINT N'THẤT BẠI, YÊU CẦU NHẬP MÃ NHÂN VIÊN Ở ĐẠI LÝ 3 BẮT ĐẦU BẰNG: NVDL3'
				ROLLBACK TRAN
			END
	END
	----DL4
	ELSE IF @MADL ='DL4'
	BEGIN
		IF (@MANV LIKE 'NVDL4%')
			BEGIN
				PRINT N'THÀNH CÔNG'
			END
		ELSE 
			BEGIN 
				PRINT N'THẤT BẠI, YÊU CẦU NHẬP MÃ NHÂN VIÊN Ở ĐẠI LÝ 4 BẮT ĐẦU BẰNG: NVDL4'
				ROLLBACK TRAN
			END
	END
	---
	ELSE IF @MADL ='DL5'
	BEGIN
		IF (@MANV LIKE 'NVDL5%')
			BEGIN
				PRINT N'THÀNH CÔNG'
			END
		ELSE 
			BEGIN 
				PRINT N'THẤT BẠI, YÊU CẦU NHẬP MÃ NHÂN VIÊN Ở ĐẠI LÝ 5 BẮT ĐẦU BẰNG: NVDL5'
				ROLLBACK TRAN
			END
	END
	ELSE IF @MADL ='DL6'
	BEGIN
		IF (@MANV LIKE 'NVDL6%')
			BEGIN
				PRINT N'THÀNH CÔNG'
			END
		ELSE 
			BEGIN 
				PRINT N'THẤT BẠI, YÊU CẦU NHẬP MÃ NHÂN VIÊN Ở ĐẠI LÝ 6 BẮT ĐẦU BẰNG: NVDL6'
				ROLLBACK TRAN
			END
	END
	ELSE IF @MADL ='DL7'
	BEGIN
		IF (@MANV LIKE 'NVDL7%')
			BEGIN
				PRINT N'THÀNH CÔNG'
			END
		ELSE 
			BEGIN 
				PRINT N'THẤT BẠI, YÊU CẦU NHẬP MÃ NHÂN VIÊN Ở ĐẠI LÝ 7 BẮT ĐẦU BẰNG: NVDL7'
				ROLLBACK TRAN
			END
	END
	ELSE IF @MADL ='DL8'
	BEGIN
		IF (@MANV LIKE 'NVDL8%')
			BEGIN
				PRINT N'THÀNH CÔNG'
			END
		ELSE 
			BEGIN 
				PRINT N'THẤT BẠI, YÊU CẦU NHẬP MÃ NHÂN VIÊN Ở ĐẠI LÝ 8 BẮT ĐẦU BẰNG: NVDL8'
				ROLLBACK TRAN
			END
	END
END